### ISSUE TITLE
TypeError: add_extension() got an unexpected keyword argument 'extension'

### ISSUE THREAD

**Issue by truls** [mathiasertl/django-ca#70]
When creating a CA I get the following (XX denotes redactions). The CA appears to be successfully created in spite of this error.

Using Django 2.2.18 and django-ca 1.17.1

```
DJANGO_SETTINGS_MODULE=XX.settings.test_deployment ./manage.py init_ca --pathlen=2 --crl-url=http://ca.example.com/crl --ocsp-url=http://ocsp.ca.example.com --issuer-url=http://ca.example.com/ca.crt XX /C=XX/L=XX/O=XX/OU=XX/CN=ca.XX
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/django/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/django/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/django/venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/management/base.py", line 294, in execute
    super(BaseCommand, self).execute(*args, **options)
  File "/home/django/venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/management/commands/init_ca.py", line 207, in handle
    run_task(generate_ocsp_key, serial=ca.serial, password=options['password'])
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/tasks.py", line 64, in run_task
    return task(*args, **kwargs)
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/tasks.py", line 88, in generate_ocsp_key
    private_path, cert_path, cert = ca.generate_ocsp_key(**kwargs)
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/models.py", line 789, in generate_ocsp_key
    cert = Certificate.objects.create_cert(ca=self, csr=csr, profile=profile, subject=self.subject,
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/managers.py", line 354, in create_cert
    cert = profile.create_cert(ca, csr, **kwargs)
  File "/home/django/venv/lib/python3.8/site-packages/django_ca/profiles.py", line 242, in create_cert
    builder = builder.add_extension(**extension.for_builder())
TypeError: add_extension() got an unexpected keyword argument 'extension'

```

**Comment by mathiasertl** [comment]
OH MY. I fixed this issue a few days ago in master but didn't realize this of course would also effect existing releases!

The issue is with the newest version of `cryptography`, version 3.4 changed names of those parameters and was release after django-ca 1.17.1. Using version 3.3 for now should work fine.

The issue here is triggered when automatically generating an OCSP key. So that will have failed, but the CA is still there. Downgrading cryptography should fix the issues. The `regenerate_ocsp_keys` management command would renew the keys, as would a running Celery instance (after a while).

As this effects the current release, I will produce a patch release ASAP as well for this.

**Comment by truls** [comment]
Thanks a lot! I will look into downgrading `cryptography` in the meantime

**Comment by mathiasertl** [comment]
Minor update: 1.17.2 is running through travis right now. Will release tomorrow though (don't release when you're tired). New release will be compatible with cryptography>=2.8, includiing 3.4.

**Comment by truls** [comment]
That did the trick. Thanks again!
